### ISSUE TITLE
Allow server to run in the background

### ISSUE THREAD

**Issue by pontusstjerna** [futurepress/react-native-static-server#13]
Hello and thanks for a great library. It works fantastic. 

I am just curious if it is somehow possible to allow the server to run while the app is in the background. I am using the library for redirection purposes, so the user opens a browser which then opens the localhost where my static file is. The problem is that as fast as I leave the app, the server shuts down. 

Thanks in advance.

**Comment by fchasen** [comment]
Adding an property to not shut the server down in the background makes sense.

**Comment by pontusstjerna** [comment]
It was easy to fix, simply remove a few lines from index.js but as you say, having it as an option would be really nice.

**Comment by Stophface** [comment]
@pontusstjerna Could you say which lines you removed?

**Comment by fchasen** [comment]
Updated to allow passing `new StaticServer({ keepAlive: true })`
