### ISSUE TITLE
There are several files providing this module. after install static-server.

### ISSUE THREAD

**Issue by inv2004** [futurepress/react-native-static-server#16]
// everything is the latest version for today
npm install --save react-native-static-server
react-native link react-native-static-server

react-native android-run
Loading dependency graph, done.
Bundling `index.js`  [development, non-minified]  0.0% (0/1), failed.

error: bundling failed: ambiguous resolution: module `C:\Users\unknown\test\index.js` tries to require `react-native`, but there are several files providing this module. You can delete or fix them:

  * `C:\Users\unknown\test\node_modules\react-native-static-server\node_modules\react-native\package.json`
  * `C:\Users\unknown\test\node_modules\react-native\package.json`

Do you know what could be the root cause of the problems?

Thank you,

**Comment by Vilitsa** [comment]
Try to delete 'C:\Users\unknown\test\node_modules\react-native-static-server\node_modules\react-native' and do npm start -- --reset-cache.
It's help me

**Comment by fchasen** [comment]
What version on RN are you using?

**Comment by inv2004** [comment]
@fchasen 

>react-native --version
react-native-cli: 2.0.1
react-native: 0.49.3

Initial problem was during installation of epubjs-rn.

**Comment by inv2004** [comment]
Looks like npm start -- --reset-cache did not help. But npm start --reset-cache helped.
I reinstalled it via npm install --save epubjs-rn (without package.json modification from readme).
react-native link
react-native run-android

And, unfortunately, I have the following problem now:

> :app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
C:\Users\unknown\Test\android\app\src\main\java\com\test\MainApplication.java:6: error: package com.futurepress.staticserver does not exist
import com.futurepress.staticserver.FPStaticServerPackage;
                                   ^
C:\Users\unknown\Test\android\app\src\main\java\com\test\MainApplication.java:7: error: package com.futurepress.staticserver does not exist
import com.futurepress.staticserver.FPStaticServerPackage;

**Comment by inv2004** [comment]
Issue is resolved by manual installation of all dep modules
