### ISSUE TITLE
Response 304

### ISSUE THREAD

**Issue by egormerkushev** [futurepress/react-native-static-server#2]
[Original issue in NanoHttpd repo](https://github.com/NanoHttpd/nanohttpd/issues/268)

I have RN app with `WebView` that shows local stored files via `react-native-static-server`. I run and stop server every time when `WebView` is created. On iOS it works fine, but on Android server returns 304 response like described in original issue.

Can you implement any solutions for this problem? May be it can be a some flag or property of server that turns on and off it solution. Thank you!

**Comment by fchasen** [comment]
Thanks for sharing that issue, I've implemented the fix mentioned there in `0.1.7`.
Only Android uses NanoHttpd, so no switch need.
