### ISSUE TITLE
I follow the steps on the Android mobile phone, such as map error

### ISSUE THREAD

**Issue by jishuke** [futurepress/react-native-static-server#22]
![wechatimg352](https://user-images.githubusercontent.com/17639749/33115621-9a5b0744-cf9c-11e7-9cfe-544ecb9efdff.jpeg)

When I put it into Android, he reported this mistake. Please help me.

**Comment by Bubblecoding** [comment]
name == null

**Comment by naltimari** [comment]
try: let server = new StaticServer(9000, "/");
