### ISSUE TITLE
Android: how to serve statics from assets folder?

### ISSUE THREAD

**Issue by naltimari** [futurepress/react-native-static-server#23]
I did some tests and right now there's no way to point the StaticServer to a 'www_root' on the assets folder on Android. I think storing the static files as assets is a straightforward way, but I couldn't find a way to make it work.

Any ideas?

p.s. RNFS.DocumentDirectoryPath is **not** where the assets are stored

**Comment by Taffyw** [comment]
me too do you success?

**Comment by jishuke** [comment]
I use this http://10.0.3.15:9000/18.jpg  but I can't access the pictures I store, what should I do

**Comment by jishuke** [comment]
Do I have your success, too? @naltimari @Taffyw @fchasen @frangeris

**Comment by naltimari** [comment]
I couldnt make it work, but I did some research and it seems Android stores assets in a different way than iOS, so much so that the Android Sdk has an AssetManager class. I’m not sure this can be pulled off without writing a request handler that uses this Api for Android

**Comment by Noitidart** [comment]
Duplicate issue here - https://github.com/futurepress/react-native-static-server/issues/6

Anyone find a solution? For both android and ios?

**Comment by kanalasumant** [comment]
@Noitidart This is what I observed on simulators only.
```
import RNFS from "react-native-fs";
import StaticServer from "react-native-static-server";

const path =
  Platform.OS === "ios"
    ? `${RNFS.DocumentDirectoryPath}/`
    : "/storage/emulated/0/Download/";

let server = new StaticServer(8082, path);
async componentDidMount() {
  const result = await server.start();
}
```
Appropriate path is set depending on the OS. Tweak the 'DocumentDirectoryPath' or the directory path from where you wanna serve appropriately and the server is run as shown above.
Now for the fun part, when you wanna actually serve a file from 'example' directory which is present directly in the path variable, this seems to work for IOS:
```
 <WebView
        source={{ uri: `http://localhost:8082/${this.props.path}/index.html` }}
        style={{ flex: 1 }}
        javaScriptEnabled={true}
      />
```
and for Android,
```
 <WebView
        source={{ uri: `http://localhost:8082/${this.props.path}` }}
        style={{ flex: 1 }}
        javaScriptEnabled={true}
      />
```

**Comment by fchasen** [comment]
You'll need to copy the files you want to server from the assets folder to the `RNFS.DocumentDirectoryPath` using `RNFS.copyFileAssets` : https://github.com/itinance/react-native-fs#copyfileassetsfilepath-string-destpath-string-promisevoid
