### ISSUE TITLE
Remove .git folder from npm registry

### ISSUE THREAD

**Issue by sampsasaarela** [futurepress/react-native-static-server#24]
Seems that `.git` -folder is added to npm registry and I think it shouldn't be there.

Now this package causes `react-native-static-server: Appears to be a git repo or submodule` -error when try to perform `react-native-git-upgrade` and `react-native-static-server` is installed from npm registry.

Solution is to manually remove `node_modules/react-native-static-server/.git` -folder or install package directly from github.

**Comment by fchasen** [comment]
Should be fixed in 0.2.4 by adding a .git to .npmignore
