### ISSUE TITLE
Accessing static assets from a WebView

### ISSUE THREAD

**Issue by leefsmp** [futurepress/react-native-static-server#25]
One obvious reason one would want to run a local server in a react native app would be to load static assets in a WebView... so I'm wondering if you have that kind of sample or experiment any of that? 

I am trying to load an html in a WebView on iOS and getting the error below:

![screen shot 2017-12-13 at 16 25 31](https://user-images.githubusercontent.com/4352502/33928849-529be69e-e022-11e7-9af4-e181d7e0a5b3.png)

**Comment by kevinold** [comment]
Are you connecting to http://0.0.0.0/ via the React Native WebView uri?

**Comment by fchasen** [comment]
This use case should work just fine, so would need some more information to debug.

Depending on the options you started it with the url should be something like http://localhost:8080/index.html
