### ISSUE TITLE
a problem on android

### ISSUE THREAD

**Issue by Taffyw** [futurepress/react-native-static-server#27]
Hello, how can in android www be added to the project
INTERNAL ERROR: given path is not a directory (/data/user/0/com.reactappdemo/files/www).

**Comment by fchasen** [comment]
Using a library like `react-native-fs` you can add the www folder with RNFS.mkdir().

I've added an example app that does that.

**Comment by DanielDanaee** [comment]
I still face this issue. What is the solution?
