### ISSUE TITLE
http://10.0.3.15:1327/18.jpg   I can't access 

### ISSUE THREAD

**Issue by jishuke** [futurepress/react-native-static-server#28]
I use this react-native-fs and react-native-static-server storage network to download the picture, but I can't access what I should do @frangeris @fchasen @JakeHartnell @sampsasaarela @AJRenold
Please help me, thank you.
![2121212](https://user-images.githubusercontent.com/17639749/34660672-0383b502-f47f-11e7-9ea5-97e330846792.jpg)

**Comment by fchasen** [comment]
Hard to tell what is going on without more information, but this doesn't seem to be an issue in the library.
