### ISSUE TITLE
Https - to open a local manifest.plist

### ISSUE THREAD

**Issue by digitalhobo** [futurepress/react-native-static-server#3]
Hi Thanks for the module

Is their any way to create a https server
as I would like to open a web view with a link to open locally stored manifest file that can install an app.

itms-services://?action=download-manifest&url=https://127.0.0.1:8080/manifest.plist

for example

Thanks in advance.
:0)

**Comment by fchasen** [comment]
Unfortunately GCDWebServer doesn't support https.

**Comment by kesha-antonov** [comment]
@fchasen Hello! Is it support now?
