### ISSUE TITLE
URL is (null)://(null):(null)

### ISSUE THREAD

**Issue by GregoryBabonaux** [futurepress/react-native-static-server#35]
Hey ! 

I've an issue when i'm building on a IOS device (iPhone 6s Plus) : 

The server start at (null)://(null):(null) so nothing works. 

The config (works great in simulator) : 

`let server = new StaticServer(8080, RNFS.DocumentDirectoryPath);
  server.start().then((url) => {
      alert('Server started at ' + url)
    });
`

Note : it happens only if WIFI is turned off 

Any idea ? 

Regards

**Comment by fchasen** [comment]
If wifi is turned off, you'll only be able to use the server with `{localOnly: true}`
