### ISSUE TITLE
Wrong Android linking instructions

### ISSUE THREAD

**Issue by ToJen** [futurepress/react-native-static-server#36]
The instruction from [here](https://github.com/futurepress/react-native-static-server#android) say:

> Open up `android/app/src/main/java/[...]/MainActivity.java`
> Add `import com.futurepress.staticserver.FPStaticServerPackage;` to the imports at the top of the file
> Add `new FPStaticServerPackage()` to the list returned by the `getPackages()` method

However, imports are usually done in `android/app/src/main/java/[...]/MainApplication.java` from what I've seen with other RN projects that need linking. Also, the `getPackages` method only exists in `MainApplication.java`.

**Comment by ToJen** [comment]
@fchasen

**Comment by fchasen** [comment]
Thanks - removed, using `react-native link` is the preferred way to add the package.
