### ISSUE TITLE
{localOnly: true} option issue

### ISSUE THREAD

**Issue by kanalasumant** [futurepress/react-native-static-server#37]
Removing {localOnly: true} option on an IPhone 6 - IOS 11.2 simulator or even on an android simulator/physical device doesn't seem to open the files I wanna serve in safari or chrome or any browser, but it can serve the files through a webview on the app itself. Correct me if I'm wrong but is this what removing this option expected. Any suggestions on how to proceed next is appreciated. Thanks!

**Comment by fchasen** [comment]
Not sure what issue you are running into, but yes if you don't have localOnly you should be able to access the files at the origin returned by `server.start()` in a browser.
