### ISSUE TITLE
Server is not alive after iOS device is 'locked'

### ISSUE THREAD

**Issue by DanielHudson** [futurepress/react-native-static-server#39]
keepAlive works fine when the app is in the background, however when the device is locked or goes into standby the server is no longer running in the background, or when the app is put into the foreground again.

Not sure if keepAlive is meant to support this or not, I am considering starting the server again manually once the app is 'active' as a work around for now.

**Comment by tomjohnson3** [comment]
@DanielHudson - i'm having the same issue. could you share a pull request? or perhaps we could collaborate on this? i was thinking of the same type of work-around.

**Comment by fchasen** [comment]
I not sure we there is a way to keep the server going when the phone is locked.
I'd recommend using `AppState.addEventListener('change')` and just starting the server again.
