### ISSUE TITLE
Android Not Serving Website

### ISSUE THREAD

**Issue by elmbrent** [futurepress/react-native-static-server#46]
Hi, 

My app works correct on IOS but fails on Android. The assets have been downloaded and stored onto the device, that are located here  /data/user/0/com.springboard/files/11 and then served via the Static Server.

The path the assets are download to is RNFS.DocumentDirectoryPath + '/11'

```
          RNFS.exists(RNFS.DocumentDirectoryPath + '/11').then((result)=> {
                //Check files are there..
                if(result){
                    webserver = new StaticServer(8080, RNFS.DocumentDirectoryPath + '/11/index.html')
                    webserver.start().then((url) => {
                        dispatch({type: types.APP_VISABILITY, payload: url})
                    })
                }
            })
```

But when the web view is loaded it seems to have the error 
"net::ERR_CONNECTION_REFUSED"

Any ideas?

**Comment by elmbrent** [comment]
Fixes by adding local only.

**Comment by bfelbo** [comment]
@elmbrent can you expand a bit on what you did?

We're having the same issue.
