### ISSUE TITLE
Redirection

### ISSUE THREAD

**Issue by andrepcg** [futurepress/react-native-static-server#49]
Is there any way to redirect all requests to index.html, for example? Or any other approach to this?

**Comment by fchasen** [comment]
It's certainly possible with the underlying native libraries, but not sure how the static server could expose those features / what the use case is.

Going to close this for now, but open to suggestions on the topic.

**Comment by pranav-xx** [comment]
@fchasen One such use case can be to support SPA client side routes. For example any request for /users/info should also be redirected to index.html 

@andrepcg How did you solve this for your need?
