### ISSUE TITLE
Help... I Got error Name==null

### ISSUE THREAD

**Issue by x5c** [futurepress/react-native-static-server#5]

**Comment by Stophface** [comment]
@x5c Did you solve it? I get the same error.

**Comment by Bubblecoding** [comment]
When I put it into Android, he reported this mistake. Please help me.

**Comment by Bubblecoding** [comment]
I follow the steps on the Android mobile phone, such as map error
![wechatimg352](https://user-images.githubusercontent.com/17639749/33115545-5cd20530-cf9c-11e7-9084-2b9650584b8a.jpeg)

**Comment by Stophface** [comment]
The docs are a little missleading @Bubblecoding 
Make sure you pass it a `port`, even if it says that it defaults to some value.
Further, pass it a `path` to a folder where the server is running on.

**Comment by Bubblecoding** [comment]
@Stophface 
port and path two parameters needed to pass on Android? Is default localhost not available?

**Comment by Stophface** [comment]
@Bubblecoding Nope. I got the same error when I relied on default localhost. Pass it `8080` or whatever, and it should work :)

**Comment by Bubblecoding** [comment]
@Stophface  My code is like this


import StaticServer from 'react-native-static-server';
let server = new StaticServer(8080);
// Start the server
server.start().then(url => {
  console.log('Serving at URL', url);
});

**Comment by Bubblecoding** [comment]
@Stophface How did you solve it? Can you explain it in detail? Thank you

**Comment by Stophface** [comment]
@Bubblecoding what is `url`?  That should be a `path` to a folder in your filesystem on the device. 

Something like

```
let server = new StaticServer(8080, '/path/to/folder');

server.start().then(url => {
    console.log('Serving at URL', url);
});

```

**Comment by Bubblecoding** [comment]
Thank you. I want to interface to different /inputMoneyValue and /mdbStatus and /openDoorResult by http://192.168.8.132:8080/. What should I do?

**Comment by Stophface** [comment]
@Bubblecoding sorry, I dont understand you.

**Comment by Bubblecoding** [comment]
@Stophface Thank you. I want to interface to different /inputMoneyValue and /mdbStatus and /openDoorResult by http://192.168.8.132:8080/. What should I do?

**Comment by Bubblecoding** [comment]
@Stophface  I don't need interfaces. I'm going to do different things with different requests, URL. What do I do?

**Comment by Bubblecoding** [comment]
@Stophface Thank you for your patience in helping me. I want to turn it into a mini server, it will receive different Url such as http://192.168.8.132:8080/inputMoneyValue and http://192.168.8.132:8080/mdbStatus and it will return some data such as: JSON {"MSG": "status notification interface"}

**Comment by Stophface** [comment]
@Bubblecoding I am not sure if this library is the correct one for doing this

The docs say

> StaticServer serves from the document directory (default) or takes an optional absolute path to serve from.

It says *document directory* or *absolute path*. As far as I understand it, it needs a folder to serve from. Maybe overthink what you are doing or consider another library.
