### ISSUE TITLE
FPStaticServer is undefined (Android)

### ISSUE THREAD

**Issue by AndreevskiAleksandar** [futurepress/react-native-static-server#52]
Hi,

I am using React Native 0.57.5 and react-native-static-server 0.3.0.
The constructor of the rn static server runs without problems. When the code reaches to call the native module `FPStaticServer.start` it throws an exception saying that the FPStaticServer object is undefined.  
I guess there is a problem in the native module link with the javascript.
Anyone with similar problems or a solution to this one?

**Comment by fchasen** [comment]
Not sure how to reproduce this, it's working fine for on RN 0.58 on Android as far as I can tell

**Comment by RandunuK** [comment]
Make sure you've linked correctly.
react-native link react-native-static-server
