### ISSUE TITLE
(Android) Serve files from assets?

### ISSUE THREAD

**Issue by 0is1** [futurepress/react-native-static-server#6]
Hi and thanks for this nice RN module!

This might be stupid question, but I wonder if it's possible to serve html/js/css-files from assets? (in Android)

So if I use filesystem, I'm using `file:///android_asset/web/index.html`-uri in `WebView` but I would like to use `http://127.0.0.1:8080` as an uri with react-native-static-server serving files from that assets path.

If it's not possible to do that, what is the best way to copy files from assets to `/data/data/com.xxx/files/whatever`?

This seems to be very simple with iOS where you can just use `"MainBundlePath"/whatever` as a path and put your html/js/css-files in that folder.

**Comment by x5c** [comment]
hi guys, u can do it...
lets make folder in your storage and do that

let path = RNFS.ExternalStorageDirectoryPath + '/www';

it worked for me

**Comment by 0is1** [comment]
Yeah, well that works but it feels kind of stupid to copy 20+ files from assets to `ExternalStorageDirectoryPath/something` :)

**Comment by Noitidart** [comment]
@0is1 did you find solution for this? I also want to server from assets folder. What was your solution on iOS by the way?

**Comment by 0is1** [comment]
@Noitidart yeah well I guess that example mentioned above was working (it's long time ago so I don't remember exactly anymore).

Here's some code I tested back then:
* https://github.com/HSLdevcom/react-native-proto/blob/local-reittiopas-bundle/index.js#L24-L34
* https://github.com/HSLdevcom/react-native-proto/blob/local-reittiopas-bundle/app/components/InlineWebView.js#L92-L101

**Comment by Noitidart** [comment]
Thanks @0is1 I moved away from trying to use this, had too many issues. Will report back letting you know if I get that to work if i get back to using this.

**Comment by x5c** [comment]
this not best practice guys, i moved to native android now and all work fine...

**Comment by Noitidart** [comment]
@x5c do you mean you have another native module for react-native? Or you ditched react-native?
