### ISSUE TITLE
How add the `www` folder so code can access in runtime?

### ISSUE THREAD

**Issue by frangeris** [futurepress/react-native-static-server#8]
First, thanks the lib 👍 

I'm having some issues trying to access to the `index.html` from the browser, everything seems to be working fine but I can't get it running pointing to my `www` folder, **I know there is not issue with the lib**, the error is `This 192.168.1.36 page can’t be found` because locally inside the app, the folder where my index file should be, not exists, so I'm passing the `path` like this:

```javascript
    let path = fs.DocumentDirectoryPath + '/embeded'
    console.log(path)
    let server = new StaticServer(9191, path)
      server.start().then((url) => {
      console.log("Serving at URL", url);
    })
```
And my folder structure:
<img width="270" alt="screen shot 2017-06-24 at 5 02 53 pm" src="https://user-images.githubusercontent.com/811381/27511619-07ba48b4-58ff-11e7-9840-107ffdd1d31a.png">

But when I check inside the final "temporal folder" in the simulator, I don't see the `embeded` folder, so is not finding the `index.html` because the folder do not exists.

I already tried adding the folder to my xcode project, trying that the folder gets created inside the bundle app, but didn't work:
<img width="241" alt="screen shot 2017-06-24 at 5 06 06 pm" src="https://user-images.githubusercontent.com/811381/27511629-7bc53732-58ff-11e7-8eb1-8598fbccb35e.png">

This is a cry for help... any advice?

Thanks

**Comment by frangeris** [comment]
Solution in PR #9

**Comment by frangeris** [comment]
Solution in PR #9

**Comment by jishuke** [comment]
I use this react-native-fs and react-native-static-server storage network to download the picture, but I can't access what I should do @frangeris @fchasen @JakeHartnell @sampsasaarela @AJRenold  
Please help me, thank you.

**Comment by jishuke** [comment]
I can get these data  /data/user/0/com.touch/files/newfiledir/17.png

**Comment by jishuke** [comment]
![2121212](https://user-images.githubusercontent.com/17639749/34660466-81ef4ad4-f47d-11e7-97d8-3166aa646d8f.jpg)
I use this http://10.0.3.15:1327/newfiledir/18.jpg and http://10.0.3.15:1327/18.jpg but I can't access the pictures I store, what should I do
