### ISSUE TITLE
Error while following install and example instructions

### ISSUE THREAD

**Issue by vgrafe** [futurepress/react-native-static-server#81]
Hi!

I just installed Expo, ejected, then installed this module and linked it. Problem is, when calling the `start` method, the following error happens (while debugging on iphone): `Unhandled promise rejection: TypeError: null is not an object (evaluating 'FPStaticServer.start')`.

I checked and, indeed, `FPStaticServer` is not defined in the module. I tried to import it myself but not to avail. No sign if it either in the react-native types file, so I assume some error happened when it was supposed to be dynamically linked in the native modules, but I have no error messages displayed when installing/linking it.

Thanks for helping!

**Comment by vgrafe** [comment]
More info - I tried again using a bare RN project. 

After installing and linking `react-native-static-server`, I tried running `pod install` and got the following error:

```bash
[!] The `react-native-static-server` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: Git sources should specify a tag.
    - WARN  | description: The description is equal to the summary.
```

**Comment by vgrafe** [comment]
OK I just looked at the PRs, and saw that this bug is addressed by https://github.com/futurepress/react-native-static-server/pull/75.

**Comment by trollepierre** [comment]
this PR can be closed, no?
