### ISSUE TITLE
TypeFPStaticServer.start  

### ISSUE THREAD

**Issue by luojiong** [futurepress/react-native-static-server#98]

**Comment by luojiong** [comment]
react-native 0.62.2  error TypeError: null is not an object (evaluating TypeFPStaticServer.start )

**Comment by AngelSan19** [comment]
Hi @luojiong what was the solution?

**Comment by luojiong** [comment]
@AngelSan19   I will node_ Modules are cleared and re run 'yarn install & & pod install' and the app is rerun. The problem is solved

**Comment by codthing** [comment]
> @AngelSan19 I will node_ Modules are cleared and re run 'yarn install & & pod install' and the app is rerun. The problem is solved

I got the same error.
I use Expo and Windows for development. Does it need pod install?
